version: "3.8"

services:
  museum_app:
    build:
      context: .
      dockerfile: Dockerfile.museum_app
    container_name: museum_app_container
    volumes:
      - .:/app  
    environment:
      - PYTHONUNBUFFERED=1  # Per evitare buffering nell'output
