# Usa l'immagine di base di Python
FROM python:3.11-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file dei requisiti
COPY requirements.txt /app/requirements.txt

# Installa le dipendenze
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto del progetto
COPY . /app

# Comando per avviare l'applicazione
CMD ["python", "main.py"]
